version: '3.8' # The 'version' key in docker-compose refers to the format of the docker-compose file, not the application version.

services:
  app:
    image: python:3.11.0
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      /bin/sh -c "
      pyenv install 3.11.0 &&
      pyenv global 3.11.0 &&
      pip3 install pipenv &&
      pipenv install &&

      pipenv run gunicorn cakes_project.wsgi:application --log-file -"
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
